// "problems.cc" implementation file.
// Ordinary differential equation problem solvers and data writers.


#include "problems.h"
#include "rkstep.h"

#include <cmath>
#include <fstream>
#include <utility>

namespace pp {

// Models u'' = -u as a first-order system:
// y0'' = y1 (velocity)
// y1'' = -y0 (acceleration)
vector harmonic_rhs(double /*x*/, vector y) {
	return {y[1], -y[0]};
}

// Models a predator-prey LV system: dx/dt = a*x - b*x*y;
// dy/dt = d*x*y - c*y
vector lotka_volterra_rhs(double /*x*/, vector y) {
	const double alpha = 1.5;
	const double beta = 1.0;
	const double gamma = 3.0;
	const double delta = 1.0;
	return {alpha * y[0] - beta * y[0] * y[1],
		delta * y[0] * y[1] - gamma * y[1]};
}

// Uses the General Relativity equatorial motion equation: u'' + u = 1 + \eps u^2
// Reduced to first order: y0'' = y1; y1'' = 1 - y0 + eps*y0^2
std::function<vector(double, vector)> relativistic_rhs(double eps) {
	return [eps](double /*phi*/, vector y) {
		return vector{y[1], 1.0 - y[0] + eps * y[0] * y[0]};
	};
}

// Sets up the Newtonian equations of motion for 3 planar bodies:
// m_i * dv_i/dt = sum(G * m_i m_j / r^2)
// Uses 12-component vectors mapped as z = {v_x, v_y, ... x, y, ...}
vector three_body_rhs(double /*t*/, vector z) {
	vector dz(12);
	const double x1 = z[0], y1 = z[1];
	const double x2 = z[2], y2 = z[3];
	const double x3 = z[4], y3 = z[5];
	const double vx1 = z[6], vy1 = z[7];
	const double vx2 = z[8], vy2 = z[9];
	const double vx3 = z[10], vy3 = z[11];

	auto accel = [](double xi, double yi, double xj, double yj) {
		double dx = xj - xi;
		double dy = yj - yi;
		double r2 = dx * dx + dy * dy;
		double r3 = std::pow(r2, 1.5);
		return std::pair<double, double>{dx / r3, dy / r3};
	};

	auto a12 = accel(x1, y1, x2, y2);
	auto a13 = accel(x1, y1, x3, y3);
	auto a21 = accel(x2, y2, x1, y1);
	auto a23 = accel(x2, y2, x3, y3);
	auto a31 = accel(x3, y3, x1, y1);
	auto a32 = accel(x3, y3, x2, y2);

	dz[0] = vx1; dz[1] = vy1;
	dz[2] = vx2; dz[3] = vy2;
	dz[4] = vx3; dz[5] = vy3;
	dz[6] = a12.first + a13.first;
	dz[7] = a12.second + a13.second;
	dz[8] = a21.first + a23.first;
	dz[9] = a21.second + a23.second;
	dz[10] = a31.first + a32.first;
	dz[11] = a31.second + a32.second;
	return dz;
}

// Formatter that converts standard generic points into lines output on file.
void write_pair_data(const std::string& filename,
	const std::vector<double>& x, const std::vector<vector>& y) {
	std::ofstream fout(filename);
	for (size_t i = 0; i < x.size(); i++) {
		fout << x[i] << ' ' << y[i][0] << ' ' << y[i][1] << '\n';
	}
}

// Unpacks the polar projection generated by relativistic precession into plot layout.
void write_orbit_data(const std::string& filename,
	const std::vector<double>& phi, const std::vector<vector>& y) {
	std::ofstream fout(filename);
	fout << "# phi u x y\n";
	for (size_t i = 0; i < phi.size(); i++) {
		double u = y[i][0];
		double r = 1.0 / u;
		fout << phi[i] << ' ' << u << ' ' << r * std::cos(phi[i]) << ' ' << r * std::sin(phi[i]) << '\n';
	}
}

// Maps the three-body state vector layout into separate columns dynamically.
void write_three_body_data(const std::string& filename,
	const std::vector<double>& t, const std::vector<vector>& z) {
	std::ofstream fout(filename);
	fout << "# t x1 y1 x2 y2 x3 y3\n";
	for (size_t i = 0; i < t.size(); i++) {
		fout << t[i] << ' ' << z[i][0] << ' ' << z[i][1] << ' '
		     << z[i][2] << ' ' << z[i][3] << ' ' << z[i][4] << ' ' << z[i][5] << '\n';
	}
}

// Evaluates the harmonic oscillator across [0, 20pi] and gathers trajectory points.
std::tuple<std::vector<double>, std::vector<vector>> solve_oscillator() {
	const double pi = std::acos(-1.0);
	return driver(harmonic_rhs, 0.0, 20.0 * pi, vector{1.0, 0.0}, 0.1, 1e-8, 1e-8);
}

// Evaluates the Lotka-Volterra problem across [0, 20] units starting at (10, 5).
std::tuple<std::vector<double>, std::vector<vector>> solve_lotka_volterra() {
	return driver(lotka_volterra_rhs, 0.0, 20.0, vector{10.0, 5.0}, 0.05, 1e-8, 1e-8);
}

// Instantiates and drives the relativistic motion eq with specified eps and velocities.
std::tuple<std::vector<double>, std::vector<vector>> solve_relativistic_orbit(double eps, double u0, double up0) {
	const double pi = std::acos(-1.0);
	constexpr double hmax = 0.1;
	return driver(relativistic_rhs(eps), 0.0, 40.0 * pi, vector{u0, up0}, 0.05, 1e-8, 1e-8, hmax);
}

// Configures the planar 12-component initial figure-8 state and solves over one period.
std::tuple<std::vector<double>, std::vector<vector>> solve_three_body() {
	vector z0(12);
	z0[0] = 0.97000436;   z0[1] = -0.24308753;
	z0[2] = -0.97000436;  z0[3] =  0.24308753;
	z0[4] = 0.0;          z0[5] =  0.0;
	z0[6] = 0.4662036850; z0[7] = 0.4323657300;
	z0[8] = 0.4662036850; z0[9] = 0.4323657300;
	z0[10] = -0.93240737; z0[11] = -0.86473146;
	return driver(three_body_rhs, 0.0, 6.32591398, z0, 0.01, 1e-8, 1e-8);
}

} // namespace pp
